import { cookies } from 'next/headers'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Footer from '@/components/core/Footer'
import Navbar from '@/components/core/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const theme = cookies().get('theme')

  return (
    <html data-theme={theme?.value || 'default'} lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="min-h-screen overflow-x-hidden pt-16">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
